fix: `yarn build`
Before this commit, and since ab8bc71ff3a1762fcba0a33dab182acab86cf5fa, this command would fail:
```
error TS6059: File '<>/expo-server-sdk-node/eslint.config.ts' is not under 'rootDir' '<>/expo-server-sdk-node/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by default include pattern '**/*'
```

We want `tsconfig.json` to include `eslint.config.ts`, so that we detect type
errors in it.  However, we don't want `tsconfig.build.json` to include
it, so that `tsc` doesn't produce build output for it.

To detect this problem in the future, I added a check in the github
tests workflow.